{% set name = "pylint-flask" %}
{% set version = "0.5" %}
{% set sha256 = "8fcdbb7cbf13d8c2ac1f2230b2aa1c1b83bb3ca2bd8b76f95561cb8757a305ec" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  fn: {{ name }}-{{ version }}.tar.gz
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: {{ sha256 }}

build:
  number: 0
  script: python setup.py install

requirements:
  build:
    - python

  run:
    - python
    - pylint-plugin-utils >=0.2.1
    - pylint >=1.0
    - astroid >=1.0
    - logilab-common >=0.60.0

test:
  imports:
    - pylint_flask

about:
  home: https://github.com/jschaf/pylint-flask
  license: GPL 2
  license_file: LICENSE
  summary: pylint-flask is a Pylint plugin to aid Pylint in recognizing and understanding errors caused when using Flask

extra:
  recipe-maintainers:
    - jakirkham
