travis:
  secure:
    BINSTAR_TOKEN: s4/CfIPCK0zVd19jjQ8y5zywC9PsZxqUT1dXb96Z+NrTSA8Sxs6N9jBJun1YNDnp5t9e05o3lwSyWOVAWfJmHFWLbd0yNk6ALuzsSX4qgzNGXU2Z/mYoo50d89NzSdup165j9vvauinDV2lv7iTnrEE+u/nhdwTHBzE4KQGwQQWgQ2s6nZMVigNjY51wV5oXbRKB211Iw3MggYq6eR8fxt6JsxMGqcYq1GfBtcD9wvmjxXizN9g7PjNsrZ0aaNz9FfESh3oNXlUs9FMRQTEbl4lQbwNyYd/jNHI4soIOt7NTYQJjGKq3pgE2VOLLfiiUmjhdEeiiD/kC58sl6YB+hX0+SJHXcqrpbdMQRa87mGXNRMirix9QBsQoTiWdnHYShFni1JYlfatGcaYbjSmI46UOxMq0LcqRqVkcGeNpMF7QuiZUEVWkCJEEAEzGqLden8/Yf3M8h7Mnc2s0oZyZSTl8qsfjqF+kKQHfKaOWzleQJdZj8g7KW4SyHbgHsO07LpeffdYtnG8Y2mWTe9rMSNYDcutX+fg2v4MdBIneuf0I8b0ToNKPN0DjWoSzEc7hu0lHfysBrQrisiN0kfiKgOGBnPAwtzTiAl0fxSl2TXouQMZZynXnXpfSs8B5L4WWh5eqN8iycHWuQtNoxIcYCy19EB8vYRCPI+OJb+DlfJ8=
appveyor:
  secure:
    BINSTAR_TOKEN: ipv/06DzgA7pzz2CIAtbPxZSsphDtF+JFyoWRnXkn3O8j7oRe3rzqj3LOoq2DZp4
