travis:
  secure:
    BINSTAR_TOKEN: 0aze7YdOfb5SAs4EfIikj4qeg3RvZ7BYgxnkY9lz9r/MMW1Z6x6qhRGkWtWy/nqye8QaucfGzXO4NgDRd5BxAsKlST+bt4fSFqFDw/ub8tXATdtmful89CeT6QavUHhci/E3Umm6fLX/EQ6oomF3sG9J2pWSXh+xvZ0I43EzfMxRZGLnY2MV/KpOcJK71tHiaow70NsucBlTxW4WaRk6WALgknbvw4cBbKfWjRkC33Dt1HOc1wpH44mOFr5ZI5ppjp1GCFtrmS3YScgKTzQi1RSfXKpyPBFVquuDHXADY0VxynPvVqG8T2PmLXisH1sk8mWjs1OdJSNn/jGSxETy82jRJTpaSQBH/w7f4PSM1rLEPdnR3VDsTbkCWdXeCjO0TCCO06vHjd7vhe3qwsElH55i+lGUKINdc478DcRgCM/1hD9B4VqrL67Nc21X0pt5w+c73tT7Uyiwdum/CtZnuKAii5GIInVcb4k6rmrZkIzXPQOhkCWEGHsOZqSAxB6z84twFijOOANUeaWE2Ays2C5PBkq7aWiqafOgDnuiajgpPYuwgFWBjwECkTxL4d+1HhNbUvu6B9Q5rTyKJzCgjYy6x22iFlOyvJbLRBeMJ6j97qOrvm2/v4ast+FzjxGxB/vw+oRrdgW+fxKhJYGp+Zbi+VXd/6xRpytKuc0u4KA=
appveyor:
  secure:
    BINSTAR_TOKEN: tumuXLL8PU75WMnRDemRy02ruEq2RpNxeK3dz0MjFssnosPm2v4EFjfNB4PTotA1
conda_forge_output_validation: true
