travis:
  secure:
    BINSTAR_TOKEN: rqg9RzTZ+XCGDxDjPvLDRJi7wXsTaKF0pyVSAGXcc+y/lEvVBvlfoZJ4+whu1ArI7iIZSL+qkphx3ujz0o/7s2EhX0DbVG5NYxt5pP0rHIoEA/C28Ni9rSlkdWoEvawfq6+1fJm2VkF9RhVzUFPITwtmCrzH47Mo/sXW7JJ8GUO1RsbDAK55CT6ofZ7omPvCQMdue4S08BvX2bNFWx/aUKBAjgwXdGmnxz4caPW2N8Uqy3AP+F1ntZGDRjOoRiDY40QYPNjsoFr2yF7GwwsSJxrmHKf8CVGVHXyUx1kxOQHts2EzzQO5PhqS6ps4TYC1FwZBGEi/AQtXysXfI3T6mVzP8/kIDE8qevra6eZZp1nDxeN/CHfSpePXPiwgLcnWcRQrXY6xZD89Q9y4jV+ja9d4P4aaSnsSLELZuFAS7ElbyA426M7bjl9+U0f4p9WSEjtoG34moIEJw/ZVmcrd+7kjY7g/9V0pIf8g3I3ikFYrD1RTBDI8ZQOtnKtEv+a1m4xi0nwhgTrXZiyI7rcrrnLTampihPKCT7LvfMMltWGAoO86nFvnKuaLICl9xR9miLVT21Wnmz9Eg3mkYbs8eY9pO8ZIlUrCGNEgiiPzpglda126j9UTkFgZUx35SC4jDMuTiNDY35clOWCdcYVKoTYoJeF2qEQopAFTfa073FY=
appveyor:
  secure:
    BINSTAR_TOKEN: MP4hZYylDyUWEsrt3u3cod2sbFeRwUziH02mvQOdbjsTO/l1yIxDkP/76rSIjcGC
